@See.Idp.Web_HostAddress = http://localhost:5001

### OpenID Configuration
GET {{See.Idp.Web_HostAddress}}/.well-known/openid-configuration
Accept: application/json

### JWKS (signing keys)
GET {{See.Idp.Web_HostAddress}}/.well-known/jwks
Accept: application/json

###
